# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: "display: blog"
description: "Thoughts, tutorials, discussions, and interesting links on front end web development from the perspective of Patrick Cox, a junior front end developer based in Durham, North Carolina."
keywords: "blog, web developer, web development, web design, responsive design, JavaScript, React, Angular, Vue, HTML, CSS, Durham, Raleigh, Chapel Hill, triangle, beginner, coding, junior web developer, front-end development, tutorial, North Carolina, Patrick Cox"

# Site settings
url: https://www.displayblog.io
gems:
  - jekyll-sitemap
baseurl: ''
# baseurl: ""

# Author settings
author:
  name      : B. Patrick Cox, Jr.
  job       : Frontend Engineer
  bio       : "Durham, NC-based front-end web developer, always learning, always laughing, always drinking good coffee.  And bourbon."
  thumb     : /images/author.jpg
  email     : bpatrickcoxjr@gmail.com
  url       : http://bpcoxjr.com
  github    : http://github.com/bpcoxjr
  twitter   : http://twitter.com/display_blog
  facebook  : http://facebook.com/bpcoxjr
  linkedin  : http://linkedin.com/in/bpcoxjr

# google_analytics: UA-52446115-1
repo: http://github.com/bpcoxjr/display-blog

# comments
